// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbvsutuzecycdnnodvvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxidnN1dHV6ZWN5Y2Rubm9kdnZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc4OTc3NjgsImV4cCI6MjA1MzQ3Mzc2OH0.14UkuZdMReRH1UY-pknaFUekey131T6-oxeRYl7Op5s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);